[project]
name = "medviz-metastazix-backend"
version = "1.0.0"
requires-python = ">=3.12"
description = "Medical application to detect pulmonary nodules"
authors = [
    {name = "thomas.graveline-mercier"},
    {name = "evrard.casamayou"},
    {name = "gabin.clerbout"},
    {name = "elie.dalmas"},
    {name = "alex.dreau"}
]
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "numpy",
    "requests",
    "scikit-learn",
    "ipykernel>=7.2.0",
    "matplotlib>=3.10.9",
    "numpy>=2.2.6",
    "pandas-stubs~=2.2.3",
    "pydicom>=3.0.2",
    "scikit-image>=0.25.2",
    "scipy>=1.15.3",
    "scipy-stubs~=1.15.3",
    "simpleitk>=2.5.5",
    "tcia-utils>=3.3.1",
    "pip>=26.1.2",
    "pytest>=9.1.0",
    "pyradiomics",
    "pytest-xdist>=3.8.0",
]

[tool.uv.sources]
pyradiomics = { git = "https://github.com/AIM-Harvard/pyradiomics", rev = "8ed579383b44806651c463d5e691f3b2b57522ab" }

[tool.pytest.ini_options]
pythonpath = ["."]
addopts = "-n auto -v"
