name: CI Pipeline

on:
  push:
    branches: [ "ci-cd", "main" ]  # put "main" branch later
  pull_request:
    branches: [ "ci-cd", "main" ]  # put "main" branch later

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build Docker images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Building Docker images
        run: docker compose build
      - name: Verify Docker images
        run: |
          docker compose up -d
          sleep 15
          docker compose ps
          docker compose logs
          docker compose down

  tests:
    name: Tests with pytest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git gcc g++ cmake build-essential

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install Python dependencies
        working-directory: backend
        run: uv sync

      - name: Run tests
        working-directory: backend
        run: uv run pytest . -v

  deploy:
    name: Publish images
    runs-on: ubuntu-latest
    needs: [tests, build]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Connexion to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ghcr.io/evrard11/medviz-backend:latest

      - name: Build & push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/evrard11/medviz-frontend:latest

      - name: Build & push database-backend
        uses: docker/build-push-action@v6
        with:
          context: ./database-backend
          push: true
          tags: ghcr.io/evrard11/medviz-database-backend:latest
