name: CI Pipeline

on:
  push:
    branches: [ "ci-cd" ]  # put "main" branch later
  pull_request:
    branches: [ "ci-cd" ]  # put "main" branch later

permissions:
  contents: read

jobs:
  build:
    name: Build Docker images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Building Docker images
        run: docker compose build
      - name: Verify Docker images
        run: |
          docker compose up -d
          sleep 15
          docker compose ps
          docker compose logs
          docker compose down

  tests:
    name: Tests with pytest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git gcc g++ cmake build-essential

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install Python dependencies
        working-directory: backend
        run: uv sync

      - name: Run tests
        working-directory: backend
        run: uv run pytest . -v
    # needs: build

    # steps:
    #   - uses: actions/checkout@v4

    #   - name: Start services
    #     run: docker compose up -d

    #   - name: Unit tests (backend)
    #     run: docker compose exec -T backend uv run pytest . -v

    #   - name: Show logs on failure
    #     if: failure()
    #     run: docker compose logs

    #   - name: Stop services
    #     if: always()
    #     run: docker compose down
